# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f329b6b7492e5f7c2ce3736bc59511decb9bf94ff9bc2badc1ed4f011969d1509bec6701ae2a7f6ce37a36e4f0601e604c094e689496a6ebc0e0a2da20664ec

test:
  secret_key_base: acdbc283519caa73c674f11b203dbf2e4487e46e16d9baa3a6d745914558b4454fe7b1fc44a9d90404b71c90019b1a1746b4b240b9988a240cb485993006995c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
